name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate project list
        shell: bash
        run: |
          find ./projects -type f -name "*.lua" > ./projects/files.txt
          git log -1 --format="%at" | xargs -I{} date -d @{} +%Y/%m/%d_%H:%M:%S >> ./projects/timestamp.txt
          git rev-parse --short HEAD > ./projects/git_hash.txt

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./projects
          force_orphan: true
          allow_empty_commit: true
          destination_dir: projects
